name: Demo Build

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (public repo)
        uses: actions/checkout@v4

      - name: Privacy guard (no private tracked files)
        run: bash scripts/check-no-private.sh

      - name: Extra sample-mode check
        run: |
          set -euo pipefail
          echo "[demo-check] verifying sample mode..."
          test -f site/content.sample.json || { echo "::error::missing site/content.sample.json"; exit 1; }
          test -f site/card.sample.html   || { echo "::error::missing site/card.sample.html"; exit 1; }

      - name: Prepare demo content
        run: |
          cp site/content.sample.json site/content.json
          cp site/card.sample.html site/card.html
          ls -R site

      - name: Upload demo artifact (no deploy)
        uses: actions/upload-artifact@v4
        with:
          name: demo-site
          path: site

  # deploy:
  #   if: github.event_name == 'push' # only deploy on push, not PR
  #   needs: demo
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/deploy-pages@v4
