name: Production Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: prod-pages
  cancel-in-progress: false

jobs:
  build-prod:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://1000days.neoycn.xyz
    steps:
      - name: Checkout (public repo)
        uses: actions/checkout@v4

      - name: Privacy guard (public repo clean)
        run: bash scripts/check-no-private.sh

      - name: Checkout (private content repo)
        uses: actions/checkout@v4
        with:
          repository: YCNeo/1000-days-private-content
          token: ${{ secrets.PRIVATE_CONTENT_PAT }}
          path: private-content

      - name: Install Node (for encryption build)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build encrypted RR payload
        env:
          PRIVATE_DIR: private-content
          PUBLIC_SITE_DIR: site
          PBKDF2_ITER: 250000
        run: |
          node .github/scripts/build-private-payload.mjs

      - name: Prepare site (card stub + sample content stays)
        run: |
          # safe stub card (public version) copied to runtime card.html
          cp site/card.sample.html site/card.html
          # sample content remains for guest mode -> copy to content.sample.json if missing
          test -f site/content.sample.json || echo '{"meta":{"version":1},"sections":[]}' > site/content.sample.json
          # CNAME
          echo "1000days.neoycn.xyz" > site/CNAME
          ls -R site

      - name: Post-build sanity check
        run: |
          test -f site/private.enc.json || (echo "::error::private.enc.json missing"; exit 1)
          test -f site/card.html || (echo "::error::card.html missing"; exit 1)

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy-prod:
    needs: build-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
